### PR TITLE
Linting

### PR DESCRIPTION
**Pull request by dleske**
Fix linting errors when using either repo's `moleculew` wrapper or Molecule in a Python virtual environment.  Updated to use newer Molecule syntax for `lint:` (unfortunately breaks use of moleculew).

Minor updates to documentation.

@istvano: I am not experienced with Molecule and new to Ansible.  I have an addition to make to your module and started with forking and running the tests, which led to the linting issues, which I tried to fix so I can move on to the other additions--I hope this can be useful so please let me know if I should try something else.

In my environment the testing failed repeatedly under either the wrapper and Python 2.7 or Molecule and Python 3.9: Docker was unable to start snapd and so was unable to install microk8s.  This was reported as being `unable to find microk8s`.

### CODE REVIEW

**Comment by dleske** [comment]
I reran the molecule tests on an Ubuntu machine and have the same results as on my OS X machine, and the results are the same, whether in the linting branch or the straight fork the upstream main branch.

* `moleculew lint` finds four simple linting issues; these are fixed in the `linting` branch
* `moleculew create` complains that the prepare playbook is not configured.
* `moleculew list` is fine.
* `moleculew check` fails on trying to find the microk8s snap.

**Comment by istvano** [comment]
Hi,

Sorry I left molecule in as I coped it from my template, but it seems you can not install snap packages with molecule so at the moment we can not run automated tests.

**Comment by istvano** [comment]
Did you manage to test it any other way?

**Comment by dleske** [comment]
@istvano The only test I performed was the linting test (`molecule lint`) and it passed.  Apart from that I've been using this to build MicroK8s clusters including with HA (albeit including the code with #11).

Note this PR has no real code changes, just a few fixes to get `molecule lint` to pass.

**Review by istvano — APPROVED** [review]

**Pull request merged**
